GEMINI_CHAT_MODEL = "gemini-2.5-flash"
GEMINI_EMBEDDING_MODEL = "gemini-embedding-001"
DEFAULT_COLLECTION = "company_default_docs"
USER_COLLECTION_PREFIX = "user_docs_"
CHROMA_DB_PATH = "./chroma_db"
